# Generated by Django 2.2.2 on 2019-06-11 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('identifier', models.CharField(max_length=10, verbose_name='Identificador')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Ex: 1000.00', max_digits=20, verbose_name='Valor')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Ex: 1000.00', max_digits=20, verbose_name='Taxa de juros')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('submission_date', models.DateField(auto_now_add=True, verbose_name='Data de submissão')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.Bank', verbose_name='Banco')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.Customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['submission_date'],
            },
        ),
    ]
