# Generated by Django 2.2.2 on 2019-06-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_loancontractpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancontract',
            name='identifier',
            field=models.CharField(max_length=10, unique=True, verbose_name='Identificador'),
        ),
    ]
