# Generated by Django 2.2.2 on 2019-06-11 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0003_auto_20190611_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancontract',
            name='responsible',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
            preserve_default=False,
        ),
    ]
