# Generated by Django 2.2.2 on 2019-06-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('bank', models.CharField(choices=[('341', 'Itaú'), ('237', 'Bradesco'), ('104', 'Caixa Econômica'), ('001', 'Banco do Brasil'), ('033', 'Santander'), ('041', 'Banrisul'), ('748', 'Sicredi'), ('756', 'Sicoob'), ('077', 'Inter'), ('070', 'BRB')], max_length=5, verbose_name='Banco')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['bank'],
            },
        ),
    ]
